MapTrackAdmin.lang={
	s_DEType_StandardA			  				:"Standard A",
	s_DEType_StandardB			  				:"Standard B",
	s_DEType_Enhance				  				:"Enhance",
	s_DEType_Advance				 					:"Advance",
	s_DEType_SimpleA									:"Simple A",
	s_DEType_SimpleB									:"Simple B",
	s_DEType_SimpleC									:"Simple C",
	s_DEType_SimpleD									:"Simple D",
	s_Privilege_LimitUser		  				:"Limit",
	s_Privilege_NormalUser	  				:"Normal",
	s_Privilege_SuperUser		  				:"Super",
	s_Privilege_UnknownUser	  				:"unknow",
	s_Title_Show						 					:"::Show::",
	s_Title_Add							 					:"::Add::",
	s_Title_Edit						 					:"::Edit::",
	s_Title_Delete					 					:"::Delete::",
	s_UserManage					 						:"User Manage",
	s_CarManage						 						:"Vehicle Manage",
	s_CarDistribute				 						:"Vehicle Distribute",
	s_SubUserDistribute		 					:"Subuser Distribute",
	s_ChargeMange					 						:"Charge Manage",
	s_RegisterKeyManage		 				:"Register Key Manage",
	s_WaitForDistributeCar  			:"Wait For Distribute",
	s_WaitForDistributeUsr  			:"Wait For Distribute",
	s_OwnCar							  				:"Owner Vehicles",
	s_ValidDate						 						:"Valid Date",
	s_UsedStatus 	 					:'Used status',
	s_RegUser		 	 				:'Used User',
	s_RegTime 		 					:'Register Time',
	s_RegIP		 		 				:'Register IP',
	s_DBServerIP						  					:"Database IP",
	s_DBServerUser					  				:"Database User",
	s_DBServerPsd						  				:"Database Password",
	s_AdminUser							  					:"Administrator",
	s_AdminPsd							  					:"Password",
	s_Login									  							:"Login",
	s_LoginTooFast					  		:"Many times to login! please wait!",
	s_UserError							  		:"User or password not correct!",
	s_DBConnFail						  		:"Database connect failed!",
	s_SearchExprieUser 			:"Search Expire user",
	s_View						 					:"View",
	s_Quest						 					:"Request",
	s_Success					 					:"Success",
	s_Fail						 					:"Failed",
	s_Timeout					 					:"Time Out",
	s_Alert						 					:"Warning",
	s_Show						 					:"Show",
	s_Add							  				:"add",
	s_Modify					  				:"Modify",
	s_Clear						 					:"Clear",
	s_Del							  				:"delete",
	s_User 						     			:"Account",
	s_FName 					     		:"First Name",
	s_LName 					     		:"Last Name",
	s_Password 				     		:"Password",
	s_Tel							    		:"Tel No.",
	s_Emaill					     		:"Email",
	s_Privilege				  			:"Privilege",
	s_SuperUser				  	:"Super User",
	s_OwnUser					  :"Own Sub User",
	s_AllUser					  	:"All User",
	s_CompanyName 		     		:"Company" 	,
	s_Address					     		:"Address" 	,
	s_Remark					     		:"Remark",
	s_Search					 				:"Search",
	s_ShowAll					 		:"Show All",
	s_Refresh					 				:"Refresh",
	s_Log							 				:"Log",
	s_Exit						 				:"Exit",
	s_PleaseConfrim		 		:"Are you sure?",
	s_ReinputPassWord	 		:"Repeat",
	s_PLSSelectFirst	 :"Please select first!",
	s_Submit					 					:"Submit",
	s_Close						 					:"Close",
	s_License						    			:"Vehicle License",
	s_Sim								  		  :"Device SIM",
	s_DEType						  				:"Device Type",
	s_DEUID							  			:"Device UID"	,
	s_Money							  						:"Money",
	s_UsedDay						  			:"Used Days",
	s_GiftDay						  				:"Gift(Day)",
	s_PrevExpire				  		:"Last Expire",
	s_PriceRule					 	:"Fee($/month)",
	s_CurExpire					  		:"This Expire",
	s_StartTime					  				:"Start Time",
	s_EndTime						  				:"End Time",
	s_ExpireReport			  		:"Expire Report",
	s_BelongUser				  				:"Owner by User",
	s_CarNotOwnByUser		  	:"Still not Disturbe to user",
	s_DatabaseStatus			  				:"Status of Database",
	s_TableName						  						:"Table Name",
	s_RecordCount					  					:"Record Count",
	s_NowDBTableCount			  			:"DBTable Summary",
	s_UseableSpaceMB			  			:"Free Memory(MB)",
	s_DiskPrartition			  					:"Disk partition",
	s_ServerDiskUseSpace	  :"Server Disk Space",
	s_DBFileStatus				  		:"Status of DB File ",
	s_FileName						  						:"File Name",
	s_FileURl							  					:"File path",
	s_SizeMB							  					:"Memory(MB)",
	s_SaveTrackDay				  			:"Track History Days",
	s_SaveImageURl				  			:"Picture Path",
	s_SaveImageCount			  			:"Max Picture of vehicle",
	s_NowClearTrackTable	  		:"Delete Track Table",
	s_Save								  							:"Save",
	s_OutputExcel		  						:"Export Excel file",
	s_UserUseTimeout			  :"System has been automatically exit! Please re-lgoin",
	s_downloadBusyWait		 		:"Server busy now, please try again later",
	s_NowClearTrackAlert	 		:"This action will lead to the database server consume a large amount of system resources, please exercise caution! <br> Due to a longer processing time, the page may have lost response to, is a normal phenomenon, please don't submit!!"
};